bronze_tables:
  market_prices: bronze_market_prices
  weather: bronze_weather
  grid_events: bronze_grid_events
  asset_reference: bronze_asset_reference
  event_type_reference: bronze_event_type_reference
  market_reference: bronze_market_reference
  region_reference: bronze_region_reference
  weather_alert_reference: bronze_weather_alert_reference

silver_tables:
  market_prices: silver_market_prices
  weather: silver_weather
  grid_events: silver_grid_events
  asset_reference: silver_asset_reference
  event_type_reference: silver_event_type_reference
  market_reference: silver_market_reference
  region_reference: silver_region_reference
  weather_alert_reference: silver_weather_alert_reference
